#!/usr/bin/env bash
# refactor task1 to fit new requirements.
lsof -ti tcp:8080 | xargs kill
chmod 777 /etc/nginx/nginx.conf
sed -Ei 's/\s*#?\s*user .*/user nginx;/' /etc/nginx/nginx.conf
sed -Ei 's/(listen (\[::\]:)?80) /\180 /' /etc/nginx/sites-enabled/default
sudo -u nginx service nginx restart
