#!/usr/bin/env bash
# configure Nginx to be running and listening on port 80 of all the server’s active IPv4 IPs
sudo sed -i -e 's/listen [0-9]\+/listen 80/g' /etc/nginx/nginx.conf
sudo service nginx restart
