#!/usr/bin/env bash
# configure Nginx to be running and listening on port 80 of all the server’s active IPv4 IPs
sed -i -e 's/listen [0-9]\+/listen 80/g' /etc/nginx/sites-available/default
sudo service nginx restart
